"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Secret environment variables during development
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
LMS_CLIENT_ID = os.environ.get('LMS_CLIENT_ID')
LMS_CLIENT_SECRET = os.environ.get('LMS_CLIENT_SECRET')
CLUB_DIRECTORY_CLIENT_ID = os.environ.get('CLUB_DIRECTORY_CLIENT_ID')
CLUB_DIRECTORY_CLIENT_SECRET = os.environ.get('CLUB_DIRECTORY_CLIENT_SECRET')
LIBRARY_CARD_CLIENT_ID = os.environ.get('LIBRARY_CARD_CLIENT_ID')
LIBRARY_CARD_CLIENT_SECRET = os.environ.get('LIBRARY_CARD_CLIENT_SECRET')
TRANSCRIPT_CLIENT_ID = os.environ.get('TRANSCRIPT_CLIENT_ID')
TRANSCRIPT_CLIENT_SECRET = os.environ.get('TRANSCRIPT_CLIENT_SECRET')
STAFF_DIRECTORY_CLIENT_ID = os.environ.get('STAFF_DIRECTORY_CLIENT_ID')
STAFF_DIRECTORY_CLIENT_SECRET = os.environ.get('STAFF_DIRECTORY_CLIENT_SECRET')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if DEBUG:
    # Development
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
    HOST_BASE_URL = 'http://127.0.0.1:8000'
else:
    # Production
    ALLOWED_HOSTS = ['yourusername.pythonanywhere.com']
    HOST_BASE_URL = 'https://yourusername.pythonanywhere.com'
    

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'api',
    'lms',
    'library',
    'clubs',
    'staff',
    'transcript',
    'rest_framework',
    'django_htmx',
    'oauth2_provider',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'drf_spectacular_sidecar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_htmx.middleware.HtmxMiddleware",
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

OAUTH2_PROVIDER = {
    'OAUTH2_VALIDATOR_CLASS': 'core.oidc.CustomOAuth2Validator',
    'SCOPES': {
        'read': 'Read access',
        'write': 'Write access',
        'openid': 'OpenID Connect scope',
        'identity': 'Access to your institutional identity information, i.e. your legal name, email address, institutional ID, date of birth and status',
        'profile': 'Access to your profile information, i.e. your preferred name',
        'affiliations': 'Access to all your affiliations; course enrolments, club memberships, department information',
        'affiliations:courses': 'Access your course enrolments',
        'affiliations:clubs': 'Access your club memberships',
        'affiliations:departments': 'Access your department information',
    },
    'OIDC_ENABLED': True,
    'OIDC_RSA_PRIVATE_KEY': os.environ.get('OIDC_RSA_PRIVATE_KEY'),
    'ACCESS_TOKEN_EXPIRE_SECONDS': 36000,
    'AUTHORIZATION_CODE_EXPIRE_SECONDS': 60,
}

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

LOGIN_URL = 'core:login'
LOGIN_REDIRECT_URL = 'core:dashboard'
LOGOUT_REDIRECT_URL = 'core:index'

AUTHENTICATION_BACKENDS = [
    'oauth2_provider.backends.OAuth2Backend',
    'django.contrib.auth.backends.ModelBackend',
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    "TOKEN_OBTAIN_SERIALIZER": "api.serializers.CustomTokenObtainPairSerializer",
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'University Identity API',
    'DESCRIPTION': 'Information about members in the University. Sensitive.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# PythonAnywhere may restrict external outgoing requests,
# i.e. CSS and JS for Swagger UI.
SPECTACULAR_SETTINGS = {
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
}