# Generated by Django 6.0 on 2025-12-18 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_forenames', models.CharField(help_text='All given names and middle names exactly as they appear on the official ID.', max_length=200, null=True)),
                ('legal_surname', models.CharField(help_text='The surname exactly as it appears on the official ID (passport).', max_length=100, null=True)),
                ('preferred_name', models.CharField(blank=True, help_text='Given by the user.', max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Identities',
            },
        ),
    ]
