# Generated by Django 6.0 on 2025-12-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identity',
            options={'verbose_name_plural': 'Identities'},
        ),
    ]
