# Generated by Django 6.0 on 2025-12-18 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_identity_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='id',
        ),
        migrations.AddField(
            model_name='identity',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
