# Generated by Django 6.0 on 2025-12-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_identity_id_identity_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identity',
            name='legal_name',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='user_id',
        ),
        migrations.AddField(
            model_name='identity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='identity',
            name='legal_forenames',
            field=models.CharField(help_text='All given names and middle names exactly as they appear on the official ID.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='legal_surnames',
            field=models.CharField(help_text='The surname exactly as it appears on the official ID (passport).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='preferred_name',
            field=models.CharField(blank=True, help_text='Given by the user.', max_length=200, null=True),
        ),
    ]
