# Generated by Django 6.0 on 2025-12-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_identity_legal_name_remove_identity_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identity',
            old_name='legal_surnames',
            new_name='legal_surname',
        ),
    ]
