# Generated by Django 6.0 on 2026-01-30 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutional_id', models.CharField(default=None, editable=False, help_text='Automatically generated.', max_length=20, unique=True)),
                ('legal_forenames', models.CharField(help_text='All given names and middle namesexactly as they appear on the official ID.', max_length=200)),
                ('legal_surname', models.CharField(help_text='The surname exactly as it appears on the official ID (passport).', max_length=100)),
                ('effective_date', models.DateField(help_text='The date a person started as their current status.')),
                ('status', models.CharField(choices=[('STU', 'Active student'), ('STA', 'Active staff'), ('ALU', 'Alumni')], default=None, max_length=20)),
                ('date_of_birth', models.DateField(default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Identities',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(help_text='Given by the user.', max_length=200)),
                ('name_type', models.CharField(help_text="For auditing. 'Preferred name', 'Nickname', 'Professional Alias', 'Maiden Name'", max_length=100, null=True)),
                ('identity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.identity')),
            ],
        ),
        migrations.CreateModel(
            name='RolesAndAffiliations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('CM', 'Club Member'), ('PF', 'Professor'), ('AD', 'Admin')], help_text='The current institutional role.', max_length=100)),
                ('affiliation_type', models.CharField(choices=[('CLUB', 'Club'), ('COURSE', 'Course'), ('DEPARTMENT', 'Department')], help_text='Specific association.', max_length=100)),
                ('affiliation_id', models.CharField(help_text='The ID of the specific group that the identity is associated with.')),
                ('is_active', models.BooleanField(default=True, help_text='Flag indicating the current validity of the role.')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.identity')),
            ],
        ),
    ]
