# Generated by Django 6.0 on 2026-01-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesandaffiliations',
            name='role_name',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('CM', 'Club Member'), ('PF', 'Professor'), ('AD', 'Admin')], help_text='The current institutional role.', max_length=100),
        ),
    ]
