# Generated by Django 6.0 on 2026-03-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
