# Generated by Django 6.0 on 2026-02-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_identitysequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='effective_date',
            field=models.DateField(help_text='The date a person started as their current status.', null=True),
        ),
        migrations.AlterField(
            model_name='rolesandaffiliations',
            name='role_name',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('CM', 'Club Member'), ('PF', 'Professor'), ('AD', 'Admin')], help_text='The current institutional role.'),
        ),
    ]
