# Generated by Django 6.0 on 2026-01-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_rolesandaffiliations_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesandaffiliations',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Flag indicating the current validity of the role.'),
        ),
    ]
