# Generated by Django 6.0 on 2026-01-29 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_rolesandaffiliations_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesandaffiliations',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.identity'),
        ),
    ]
