# Generated by Django 6.0 on 2026-03-02 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_identity_effective_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='institutional_id',
            field=models.CharField(editable=False, help_text='Automatically generated.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='identity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.identity'),
        ),
        migrations.AlterField(
            model_name='rolesandaffiliations',
            name='affiliation_type',
            field=models.CharField(choices=[('CLUB', 'Club'), ('COURSE', 'Course'), ('MODULE', 'Module'), ('DEPARTMENT', 'Department')], help_text='Specific association.', max_length=100),
        ),
        migrations.AlterField(
            model_name='rolesandaffiliations',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='core.identity'),
        ),
    ]
