# Generated by Django 6.0 on 2026-03-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_identity_institutional_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAffiliation',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Approval',
                'verbose_name_plural': 'Pending Approvals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.rolesandaffiliations',),
        ),
    ]
