# Generated by Django 6.0 on 2026-03-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_rolesandaffiliations_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesandaffiliations',
            name='affiliation_type',
            field=models.CharField(choices=[('CLUB', 'Club'), ('COURSE', 'Course'), ('MOD', 'Module'), ('DEPT', 'Department')], help_text='Specific association.', max_length=100),
        ),
    ]
