# Generated by Django 6.0 on 2026-03-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_rolesandaffiliations_affiliation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='date_of_birth',
            field=models.DateField(default=None, help_text='Date of birth.', null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='status',
            field=models.CharField(choices=[('STU', 'Active student'), ('STA', 'Active staff'), ('ALU', 'Alumni')], default=None, help_text='Status of university member.', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name_type',
            field=models.CharField(choices=[('', '--'), ('Preferred name', 'Preferred name'), ('Maiden Name', 'Maiden Name'), ('Professional Alias', 'Professional Alias'), ('Nickname', 'Nickname')], help_text="For auditing. 'Preferred name', 'Nickname', 'Professional Alias', 'Maiden Name'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_name',
            field=models.CharField(blank=True, help_text='Given by the user.', max_length=200),
        ),
    ]
