# Generated by Django 6.0 on 2026-03-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_identity_date_of_birth_alter_identity_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name_type',
        ),
    ]
