# Generated by Django 6.0 on 2026-03-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_profile_name_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesandaffiliations',
            name='role_name',
            field=models.CharField(choices=[('CLUB', [('CM', 'Club Member'), ('PR', 'President')]), ('COURSE', [('UG', 'Undergraduate'), ('PG', 'Postgraduate')]), ('MOD', [('UG', 'Undergraduate'), ('PG', 'Postgraduate')]), ('DEPT', [('PF', 'Professor'), ('AD', 'Admin')])], help_text='The current institutional role.'),
        ),
    ]
