# Generated by Django 6.0 on 2026-03-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_rolesandaffiliations_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesandaffiliations',
            name='role_name',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('CM', 'Club Member'), ('CP', 'Club President'), ('PF', 'Professor'), ('AD', 'Admin')], help_text='The current institutional role.'),
        ),
    ]
